#!/bin/bash

# Update version script for semantic-release
# This script updates version numbers across the project

set -e

VERSION=$1

if [ -z "$VERSION" ]; then
    echo "Usage: $0 <version>"
    exit 1
fi

echo "📝 Updating version to $VERSION"

# Create or update version.properties file
cat > version.properties << EOF
# Auto-generated by semantic-release
# Do not edit manually
version=$VERSION
versionCode=$(date +%Y%m%d%H%M)
EOF

echo "✅ Updated version.properties"

# Update root Package.swift if it exists
if [ -f "Package.swift" ]; then
    sed -i.bak "s/version = \".*\"/version = \"$VERSION\"/" Package.swift
    rm -f Package.swift.bak
    echo "✅ Updated Package.swift"
fi

# Update README if version is mentioned
if grep -q "from: \"" README.md 2>/dev/null; then
    sed -i.bak "s/from: \"[0-9]*\.[0-9]*\.[0-9]*\"/from: \"$VERSION\"/" README.md
    rm -f README.md.bak
    echo "✅ Updated README.md"
fi

echo "✨ Version update complete: $VERSION"

