name: Run unit tests and quality checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build app and test APK
        run: |
          ./gradlew assembleDebug
          ./gradlew assembleAndroidTest

      - name: Authenticate with Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
        run: |
          echo "${{ secrets.FIREBASE_AUTH_KEY }}" | base64 --decode > firebase-key.json

      - name: Verify Firebase Authentication
        run: gcloud auth list

      - name: Verify project
        run: gcloud config list

      - name: Run Instrumentation Tests
        run: |
          gcloud auth activate-service-account --key-file=firebase-key.json
          gcloud --quiet config set project ${{ secrets.FIREBASE_PROJECT_ID }}
          gcloud firebase test android run \
            --type instrumentation \
            --app androidApp/build/outputs/apk/debug/androidApp-debug.apk \
            --test androidApp/build/outputs/apk/androidTest/debug/androidApp-debug-androidTest.apk \
            --device model=oriole,version=31,locale=en,orientation=portrait \
            --timeout 5m

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: firebase-test-results
          path: .